ticketmaster-api-staging/ticketmaster-api-staging.github.io

.travis.yml
Rakefile

1. Added Rakefile with script for autodeploy.
2. Added secure token to .travis.yml for access from Travis CI to git
branches.
3. Added branches whitelist to .travis.yml.

Add: autodeploy dev branch to master branch after successful testing.

---

_sass/_fonts.scss
_sass/_vars.scss

Ref: set TMSansLEADINGFIXED instead of TMSans

---

products-and-docs/apis/discovery/index.md
products-and-docs/apis/pantheon/index.md

Added API content from Pantheon and from Apigee Discovery API console -

---

_includes/content
content/home/columns.md
products-and-docs/apis/commerce/index.md

example: {% include content id="id" %}

Added liquid fucntion for including markdown files.

---

_layouts/debug.html
content/home/columns.md
debug/index.md

ticketmaster-api-staging.github.io/debug

TKMDPA-1 Added special debug page with info about build.

---

_layouts/documentation.html
_sass/_fonts.scss
_sass/_vars.scss
_sass/components/aside-menu.scss
_sass/pages/documentation.scss
_sass/pages/parser.scss
css/main.scss
products-and-docs/apis/parser/index.md
scripts/components/parser.js
scripts/components/pd-side-menu.js

Rem: syntaxys gap

---

_includes/home-footer.html
_includes/home-header.html
_sass/_typography.scss
_sass/_vars.scss
_sass/pages/under_development.scss
assets/img/ic-under-development.svg
css/main.scss
products-and-docs/under-development/index.md

add: TKM-DPA-36 Under Development page layout: Desktop and Responsive have been implemented

Tkm dpa 36

---

_layouts/documentation-single.html
_layouts/documentation.html
_sass/_base.scss
_sass/_vars.scss
_sass/components/aside-menu.scss
_sass/components/top-bar.scss
scripts/components/pd-side-menu.js

mod; TKM-DPA-11 TKM-DPA-12 test deployment for further polishing

Tkm dpa 11 12

---

.gitignore
_sass/pages/documentation.scss
products-and-docs/apis/discovery/index.md
scripts/components/parser.js

Content render pd

---

_sass/_base.scss
_sass/_typography.scss
_sass/_vars.scss
_sass/components/aside-menu.scss
_sass/pages/documentation.scss

Add line-heights for typography

Mod: typography style

---

_sass/_base.scss
_sass/_typography.scss
_sass/_vars.scss
_sass/pages/documentation.scss

Add: new margin styles

---

scripts/components/pd-side-menu.js

fix: side menu background disappears on anchor link click

Menu anchor bg fix

---

_includes/pd-side-menu.html
assets/img/getting-started/ic-cart.svg
assets/img/getting-started/ic-user.svg
products-and-docs/apis/deals-api/index.md
products-and-docs/apis/getting-started/index.md

Mod: set static IDs in Deals-Api.md

Add: rows in second table

---

products-and-docs/under-development/index.md

Mod: under-dev text and links

---

products-and-docs/apis/commerce/index.md
products-and-docs/apis/discovery/index.md
products-and-docs/apis/international-discovery/index.md

Mod: cURL as multilines

---

scripts/components/parser.js
scripts/components/request-response.js

Sprint 4 bug fixing

---

_sass/pages/partners.scss
partners/list/002-nexus.md

Mod: form bottom margin

---

_layouts/documentation.html
_sass/components/table-collapse.scss
css/main.scss
scripts/components/table-collapse.js

Add collapse for big tables

---

_sass/components/table-collapse.scss
assets/img/products-and-docs/ic-shevron-down-blue.svg
scripts/components/table-collapse.js

Add tooltips.
Remove bottom gradient.
Fix bug with resize.

Add collapse button highlight.

---

_includes/feedback.html
_layouts/default.html
_sass/_vars.scss
_sass/components/feedback.scss
scripts/components/feedback.js

Pay attention:
in Amazon url //s3.amazonaws.com/ki.js/63104/etg.js".
63104 - account ID.
etg.js - dinamic js file
Trial request limit - 30

Integrate feedback with 'Qualaroo'

---

_includes/partials/footer.html
_layouts/blogs.html
_sass/components/bottom-bar.scss
_sass/pages/blogs.scss
products-and-docs/index.md
support/index.md
tests/galen/all.test
tests/galen/products-and-docs/common/footer-desktop.gspec
tests/galen/products-and-docs/common/footer-mobile.gspec
tests/galen/products-and-docs/common/footer-tablet.gspec

Mod: white footer padding
Mod: links in footer

Add: hover effect in blue and white footer

---

_includes/support-side-menu.html
index.md
partners/certified-partners/index.md
support/index.md

Mod: links to forum, link to ApiExplorer

---

_sass/pages/documentation.scss

Rem: bottom margin for mobile tabs menu

Mod: padding-bottom for selected tab

---

partners/startups-and-developers/articles/api-devjam-in-durham.md
partners/startups-and-developers/articles/cpi-devjam-in.md
partners/startups-and-developers/index.md

Mod: hide articles "Ticketmaster at HackPoly"

Mod:  link to apiExplorer, text

---

_includes/pd-side-menu.html
assets/img/getting-started/ic-publish.svg
assets/img/products-and-docs/ic-publish.svg
products-and-docs/apis/getting-started/index.md
products-and-docs/apis/publish/index.md
products-and-docs/index.md

The new Publish API needs a documentation on http://developer.ticketmaster.com/

Addition of the Publish API documentation

---

_includes/feedback.html
_includes/partials/footer.html
_includes/white-footer.html
_layouts/blogs.html
partners/certified-partners/nexus/index.md
products-and-docs/apis/getting-started/index.md
support/contact-us/index.md

Mod: email checker
Mod: table in 'getting-started'

Add: link in footer to contact-us page

---

_sass/pages/contact-us.scss
assets/img/getting-started/ic-archtic.svg
assets/img/getting-started/ic-flag.svg
assets/img/products-and-docs/ic-archtic.svg
products-and-docs/apis/archtics/index.md
products-and-docs/apis/getting-started/index.md
products-and-docs/index.md
support/contact-us/index.md

Mod: contactUs page autofocus off

Mod: arcticsAPI -links

---

_includes/feedback.html
_sass/_base.scss
_sass/components/common-dialog.scss
_sass/pages/contact-us.scss
scripts/components/feedback.js
support/contact-us/index.md

add: show long msg error (contactus and feedback)

ad: form reset

---

_includes/release-notes.html
_sass/pages/tutorials.scss
products-and-docs/tutorials/events-search/index.md
products-and-docs/tutorials/widgets/index.md

mod: tutorial buttons

---

partners/startups-and-developers/articles/discovery-heatmap.md

Add Discovery Heatmap article to partners/startups-and-developpers

Add Discovery API Heatmap to the website

---

_includes/swagger.html
_sass/pages/documentation.scss
scripts/components/autodoc-show-all.js

fix: replace spaces in start and end of string

---

tests/serenity/src/main/java/bla/tm/pages/site/products_and_docs/PD_InventoryStatusAPIPage.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_InventoryStatusAPISteps.java
tests/serenity/src/test/java/bla/tm/definitions/site/products_and_docs/PD_InventoryStatusAPIDefinition.java
tests/serenity/src/test/resources/stories/site/products_and_docs/PD_InventoryStatusAPI.story
tests/serenity/src/test/resources/stories/site/products_and_docs/PD_SDKs.story
tests/serenity/src/test/resources/stories/site/widgets/APIKeyReplacementNegative.story

- create story file with common scenario which checks Disqus, Left Menu and header

- add Inventory status Api Page with Definition, Steps, and Page Object

---

tests/serenity/src/main/java/bla/tm/pages/site/EventsPage.java
tests/serenity/src/main/java/bla/tm/pages/site/products_and_docs/PD_Widget_CalendarPage.java
tests/serenity/src/main/java/bla/tm/pages/site/products_and_docs/PD_Widget_CountdownPage.java
tests/serenity/src/main/java/bla/tm/pages/site/products_and_docs/PD_WidgetsPage.java
tests/serenity/src/main/java/bla/tm/staticmethods/StaticMethods.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_Widget_CalendarSteps.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_Widget_CountdownSteps.java
tests/serenity/src/main/java/bla/tm/widgets/AnsestorWidget.java
tests/serenity/src/main/java/bla/tm/widgets/AnsestorWidgetImpl.java
tests/serenity/src/main/java/bla/tm/widgets/CalendarWidget.java
tests/serenity/src/main/java/bla/tm/widgets/CalendarWidgetImpl.java
tests/serenity/src/main/java/bla/tm/widgets/CountdownWidget.java
tests/serenity/src/main/java/bla/tm/widgets/CountdownWidgetImpl.java
tests/serenity/src/test/java/bla/tm/definitions/site/products_and_docs/PD_Widget_CalendarDefinition.java
tests/serenity/src/test/java/bla/tm/definitions/site/products_and_docs/PD_Widget_CountdownDefinition.java
tests/serenity/src/test/java/bla/tm/definitions/site/products_and_docs/PD_WidgetsDefinition.java
tests/serenity/src/test/java/bla/tm/definitions/site/widgets/CalendarWidgetDefinition.java
tests/serenity/src/test/java/bla/tm/definitions/site/widgets/CountdownWidgetDefinition.java
tests/serenity/src/test/resources/stories/site/products_and_docs/PD_Widget_Calendar.story
tests/serenity/src/test/resources/stories/site/products_and_docs/PD_Widget_Countdown.story
tests/serenity/src/test/resources/stories/site/products_and_docs/PD_Widgets.story
tests/serenity/src/test/resources/stories/site/widgets/APIKeyReplacementPositive.story
tests/serenity/src/test/resources/stories/site/widgets/CalendarWidget.story
tests/serenity/src/test/resources/stories/site/widgets/CountdownWidget.story

Please, review this chunk of code

Automation tsekh

---

_includes/widget-config.html
_layouts/default.html
_sass/components/lazy-select.scss
scripts/components/lazy-selector.js

add: selector to EDW

---

_layouts/base-content.html
scripts/components/support-side-menu.js

mod: logic of menu render

---

_includes/lazy-selector-modal.html
_sass/components/lazy-select.scss
scripts/components/lazy-selector.js

mod: style button

---

_sass/explorer/style.scss
scripts/components/lazy-selector.js

mod: style input

---

_includes/lazy-selector-modal.html
_sass/components/lazy-select.scss
scripts/components/classification-selector.js
scripts/components/lazy-selector.js

add: mobile style

---

_sass/components/lazy-select.scss
scripts/components/lazy-selector.js

rem: full screen map button

---

_sass/pages/documentation.scss

mod: right padding according TKMDPA-1548

---

partners/certified-partners/nexus/index.md
scripts/components/feedback.js
scripts/components/nexus-form-validate.js

add: murkup to nexus

---

_layouts/documentation.html
_layouts/tutorials-single.html
scripts/components/parser.js
scripts/components/tutorials-code.js

mod: copy button in modal

---

tests/serenity/pom.xml
tests/serenity/src/main/java/bla/tm/pages/site/products_and_docs/PD_APIExplorerV2Page.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_APIExplorerV2Steps.java
tests/serenity/src/test/java/bla/tm/definitions/site/products_and_docs/PD_APIExplorerV2Definition.java
tests/serenity/src/test/resources/stories/site/products_and_docs/PD_APIExplorer_V2.story

Tkmdpa 4536

---

tests/serenity/pom.xml
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_CommonSteps.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_Widget_EventDiscoverySteps.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_Widget_MapSteps.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/WidgetFields.java
tests/serenity/src/main/java/bla/tm/widgets/AnsestorWidgetImpl.java
tests/serenity/src/main/java/bla/tm/widgets/EventDiscoveryWidget.java
tests/serenity/src/main/java/bla/tm/widgets/EventDiscoveryWidgetImpl.java
tests/serenity/src/test/java/bla/tm/definitions/site/products_and_docs/PD_Widget_MapDefinition.java
tests/serenity/src/test/java/bla/tm/definitions/site/widgets/EventDiscoveryWidgetDefinition.java
tests/serenity/src/test/resources/stories/site/widgets/EventDiscoveryWidget.story

fixes according
https://jira.epam.com/jira/browse/TKMDPA-4650

Fixed failed test case [EDW]&[MapW] [*.java]

---

tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_Widget_EventDiscoverySteps.java
tests/serenity/src/main/java/bla/tm/widgets/AnsestorWidget.java
tests/serenity/src/main/java/bla/tm/widgets/AnsestorWidgetImpl.java
tests/serenity/src/test/java/bla/tm/definitions/site/widgets/EventDiscoveryWidgetDefinition.java
tests/serenity/src/test/resources/stories/site/widgets/EventDiscoveryWidget.story

Investigate failed  automation tests

Tkmdpa 4672

---

tests/serenity/src/test/resources/stories/site/products_and_docs/PD_SDKs.story

small fix
please do not delete branch

Small changes

---

_config.yml
_includes/head.html
products-and-docs/apis/publish-api/index.md
spec/specs/widgets/countdown/countdown.spec.js

add: open graph meta tegs

---

.travis.yml
tests/serenity/src/main/java/bla/tm/pages/AncestorPage.java
tests/serenity/src/main/java/bla/tm/pages/site/products_and_docs/PD_APIExplorerV2Page.java
tests/serenity/src/main/java/bla/tm/steps/AnyPageSteps.java
tests/serenity/src/main/java/bla/tm/steps/products_and_docs/PD_APIExplorerV2Steps.java
tests/serenity/src/test/java/bla/tm/definitions/site/products_and_docs/PD_APIExplorerV2Definition.java
tests/serenity/src/test/resources/stories/site/products_and_docs/PD_APIExplorer_V2.story

for successful running of tests i need last version of firefox on travis

Update firefox version on Travis

---

tests/serenity/src/main/java/bla/tm/pages/pantheon/AddNewAppPage.java
tests/serenity/src/main/java/bla/tm/steps/pantheon/UserAppsSteps.java
tests/serenity/src/test/resources/stories/site/pantheon/UserApps.story

Refactoring failed test cases

---

tests/serenity/src/test/java/bla/tm/preconditions/Before_User_Story.java

merge this request ASAP, please

Refactored @BeforeStory on  @BeforeScenario

---

.travis.yml

[Automation][Travis]Update screen resolution

---

tests/serenity/pom.xml

[Automation] Fix webdriver.driver [*.xml]

---

tests/serenity/pom.xml

This reverts commit e363122757d71365826ea95a27c61aedc6c9a919.

[Automation] Revert "remove redundant repositories"

---

.travis.yml

update node js version;
npm install - to run unit tests with updated node modules to avoid conflicts.

run unit-tests on Travis

---

.travis.yml
Rakefile

disable unit test when merge with master
disable galen tests

[CI] disable unit test when merge with master

---

products-and-docs/widgets/event-discovery/1.0.0/theme/newschool.css
products-and-docs/widgets/event-discovery/1.0.0/theme/oldschool.css
products-and-docs/widgets/event-discovery/1.0.0/theme/simple.css

(cherry picked from commit f59be92)

Fix styles for the Wordpress widget
